version: '2.1'

services:
    dq.deploy:
        image: dq.deploy
        build: .
        environment:
            NODE_ENV: development
        ports:
            - 4390:80
            - 9229:9229
        ## set your startup file here
        command: node --inspect ./build/index.js
